// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6iwYf1NvlTrGH4OpzC8zpiVEmSuSrF8',
    appId: '1:806384462409:web:de2e73aa69df8d39362d98',
    messagingSenderId: '806384462409',
    projectId: 'shubhaytanam-buildtech-pvt-ltd',
    authDomain: 'shubhaytanam-buildtech-pvt-ltd.firebaseapp.com',
    storageBucket: 'shubhaytanam-buildtech-pvt-ltd.firebasestorage.app',
    measurementId: 'G-WK7440N3Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5Imwhk5IyXtn7spJnjALv8-mi6WIIS0',
    appId: '1:806384462409:android:2729ab50f6419602362d98',
    messagingSenderId: '806384462409',
    projectId: 'shubhaytanam-buildtech-pvt-ltd',
    storageBucket: 'shubhaytanam-buildtech-pvt-ltd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJ9hddxyZCupbjk1ZpOEir7H01qdl0aw',
    appId: '1:806384462409:ios:767ec3f08ced0b16362d98',
    messagingSenderId: '806384462409',
    projectId: 'shubhaytanam-buildtech-pvt-ltd',
    storageBucket: 'shubhaytanam-buildtech-pvt-ltd.firebasestorage.app',
    iosBundleId: 'com.realestate.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYJ9hddxyZCupbjk1ZpOEir7H01qdl0aw',
    appId: '1:806384462409:ios:767ec3f08ced0b16362d98',
    messagingSenderId: '806384462409',
    projectId: 'shubhaytanam-buildtech-pvt-ltd',
    storageBucket: 'shubhaytanam-buildtech-pvt-ltd.firebasestorage.app',
    iosBundleId: 'com.realestate.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo6iwYf1NvlTrGH4OpzC8zpiVEmSuSrF8',
    appId: '1:806384462409:web:88b739c0690cf5ed362d98',
    messagingSenderId: '806384462409',
    projectId: 'shubhaytanam-buildtech-pvt-ltd',
    authDomain: 'shubhaytanam-buildtech-pvt-ltd.firebaseapp.com',
    storageBucket: 'shubhaytanam-buildtech-pvt-ltd.firebasestorage.app',
    measurementId: 'G-KXVZXW5FY1',
  );
}
